name: GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12.3 ]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install modules
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: unit test
        run: |
          cd tests
          python --version
          python -m unittest
          cd ../
      - name: build project
        run: python -m build --sdist
